hack.md: fix instructions for Fedora
I was getting this error while building on Fedora 44:
```
iego/src/codepointer/cbuild/_deps/qhexview-src/include -isystem /home/diego/src/codepointer/cbuild/_deps/qsimpleupdater-src/include -isystem /home/diego/src/codepointer/cbuild/_deps/qjsonmodel-src/include -fPIE -Wall -Wextra -Wpedantic -fPIC -MD -MT CMakeFiles/codepointer.dir/src/plugins/TreeSitter/tree-sitter/lib/src/lib.c.o -MF CMakeFiles/codepointer.dir/src/plugins/TreeSitter/tree-sitter/lib/src/lib.c.o.d -o CMakeFiles/codepointer.dir/src/plugins/TreeSitter/tree-sitter/lib/src/lib.c.o -c /home/diego/src/codepointer/src/plugins/TreeSitter/tree-sitter/lib/src/lib.c
In file included from /home/diego/src/codepointer/src/plugins/TreeSitter/tree-sitter/lib/src/././unicode.h:13,
                 from /home/diego/src/codepointer/src/plugins/TreeSitter/tree-sitter/lib/src/./lexer.c:3,
                 from /home/diego/src/codepointer/src/plugins/TreeSitter/tree-sitter/lib/src/lib.c:4:
/home/diego/src/codepointer/src/plugins/TreeSitter/tree-sitter/lib/src/././unicode/utf8.h:37:10: fatal error: unicode/umachine.h: No such file or directory
   37 | #include "unicode/umachine.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
[146/163] Building CXX object CMakeFiles/codepointer.dir/src/plugins/ProjectManager/ProjectSearch.cpp.o
ninja: build stopped: subcommand failed.
```

Problem was a missing package (ICU):
```
root@fedora:~# dnf install libicu-devel
```